// <auto-generated />
using System;
using Client.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Infra.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20260401143451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a57d85c-39d6-4f8e-9b74-15937c7e8f10"),
                            CIN = "BE123456",
                            DateCreation = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "said.wahid@example.ma",
                            ICE = "",
                            Nom = "Said WAHID",
                            Telephone = "+212612345678",
                            TypeClient = "Particulier"
                        },
                        new
                        {
                            Id = new Guid("bc16ce57-5e0c-434b-8f23-dc0fbf5af3a1"),
                            CIN = "",
                            DateCreation = new DateTime(2026, 4, 1, 8, 15, 0, 0, DateTimeKind.Utc),
                            Email = "contact@atlas-logistics.ma",
                            ICE = "001234567000001",
                            Nom = "Atlas Logistics",
                            Telephone = "+212522334455",
                            TypeClient = "Entreprise"
                        });
                });

            modelBuilder.Entity("Client.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("Client.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LigneComplete")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Adresse");

                            b1.Property<string>("Pays")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Pays");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ville");

                            b1.HasKey("ClientId");

                            b1.ToTable("Client");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");

                            b1.HasData(
                                new
                                {
                                    ClientId = new Guid("7a57d85c-39d6-4f8e-9b74-15937c7e8f10"),
                                    LigneComplete = "12 Avenue Mohammed V",
                                    Pays = "Maroc",
                                    Ville = "Casablanca"
                                },
                                new
                                {
                                    ClientId = new Guid("bc16ce57-5e0c-434b-8f23-dc0fbf5af3a1"),
                                    LigneComplete = "Parc Technopolis, Rocade Rabat-Sale",
                                    Pays = "Maroc",
                                    Ville = "Rabat"
                                });
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
